module.exports = [
  {
    "name" : "Mike0227",
    "difficulty" : "Medium",
    "genre": "Alt/Rock",
    "songNum" : 10,
    "score" : 13,
    "correct" : 5,
    "partiallyCorrect" : 3,
    "incorrect" : 2,
    "time" : "00:45",
    "avg" : "00:05"
  },
  {
    "name" : "ErinA",
    "difficulty" : "Medium",
    "genre": "Alt/Rock",
    "songNum" : 10,
    "score" : 16,
    "correct" : 7,
    "partiallyCorrect" : 2,
    "incorrect" : 1,
    "time" : "00:57",
    "avg" : "00:06"
  },
  {
    "name" : "ErinA",
    "difficulty" : "Hard",
    "genre": "Alt/Rock",
    "songNum" : 10,
    "score" : 15,
    "correct" : 5,
    "partiallyCorrect" : 5,
    "incorrect" : 0,
    "time" : "01:15",
    "avg" : "00:08"
  },
  {
    "name" : "Mike0227",
    "difficulty" : "Medium",
    "genre": "Alt/Rock",
    "songNum" : 30,
    "score" : 72,
    "correct" : 23,
    "partiallyCorrect" : 6,
    "incorrect" : 1,
    "time" : "03:45",
    "avg" : "00:08"
  },
  {
    "name" : "Mike0227",
    "difficulty" : "Medium",
    "genre": "Pop",
    "songNum" : 30,
    "score" : 48,
    "correct" : 22,
    "partiallyCorrect" : 4,
    "incorrect" : 4,
    "time" : "02:55",
    "avg" : "00:06"
  },
  {
    "name" : "Chuckie",
    "difficulty" : "Medium",
    "genre": "Alt/Rock",
    "songNum" : 20,
    "score" : 33,
    "correct" : 14,
    "partiallyCorrect" : 5,
    "incorrect" : 1,
    "time" : "01:45",
    "avg" : "00:06"
  },
  {
    "name" : "Carson",
    "difficulty" : "Hard",
    "genre": "Pop",
    "songNum" : 22,
    "score" : 7,
    "correct" : 8,
    "partiallyCorrect" : 5,
    "incorrect" : 2,
    "time" : "01:47",
    "avg" : "00:06"
  },
  {
    "name" : "PoTheCat",
    "difficulty" : "Easy",
    "genre": "Pop",
    "songNum" : 10,
    "score" : 20,
    "correct" : 10,
    "partiallyCorrect" : 0,
    "incorrect" : 0,
    "time" : "00:45",
    "avg" : "00:05"
  },
  {
    "name" : "Mama Terry",
    "difficulty" : "Easy",
    "genre": "Pop",
    "songNum" : 20,
    "score" : 38,
    "correct" : 18,
    "partiallyCorrect" : 2,
    "incorrect" : 0,
    "time" : "01:42",
    "avg" : "00:06"
  },
  {
    "name" : "LeiaLove",
    "difficulty" : "Easy",
    "genre": "Pop",
    "songNum" : 30,
    "score" : 60,
    "correct" : 30,
    "partiallyCorrect" : 0,
    "incorrect" : 0,
    "time" : "04:10",
    "avg" : "00:09"
  },
  {
    "name" : "Larissa",
    "difficulty" : "Medium",
    "genre": "Random",
    "songNum" : 10,
    "score" : 20,
    "correct" : 10,
    "partiallyCorrect" : 0,
    "incorrect" : 0,
    "time" : "00:32",
    "avg" : "00:04"
  },
  {
    "name" : "xo_Marsha_ox",
    "difficulty" : "Medium",
    "genre": "Random",
    "songNum" : 10,
    "score" : 19,
    "correct" : 9,
    "partiallyCorrect" : 1,
    "incorrect" : 0,
    "time" : "00:36",
    "avg" : "00:04"
  },
  {
    "name" : "Larissa",
    "difficulty" : "Easy",
    "genre": "Random",
    "songNum" : 10,
    "score" : 16,
    "correct" : 6,
    "partiallyCorrect" : 4,
    "incorrect" : 0,
    "time" : "00:33",
    "avg" : "00:04"
  },
  {
    "name" : "SeanMDude",
    "difficulty" : "Hard",
    "genre": "Random",
    "songNum" : 30,
    "score" : 60,
    "correct" : 30,
    "partiallyCorrect" : 0,
    "incorrect" : 0,
    "time" : "03:50",
    "avg" : "00:08"
  }
]