module.exports = [
  {
    "name" : "Mike0227",
    "difficulty" : "Medium",
    "genre": "Alt/Rock",
    "songNum" : 10,
    "score" : 13,
    "correct" : 5,
    "partiallyCorrect" : 3,
    "incorrect" : 2,
    "time" : "00:45",
    "avg" : "00:05"
  },
  {
    "name" : "ErinA",
    "difficulty" : "Medium",
    "genre": "Alt/Rock",
    "songNum" : 10,
    "score" : 16,
    "correct" : 7,
    "partiallyCorrect" : 2,
    "incorrect" : 1,
    "time" : "00:57",
    "avg" : "00:06"
  },
  {
    "name" : "ErinA",
    "difficulty" : "Hard",
    "genre": "Alt/Rock",
    "songNum" : 10,
    "score" : 15,
    "correct" : 5,
    "partiallyCorrect" : 5,
    "incorrect" : 0,
    "time" : "01:15",
    "avg" : "00:08"
  },
  {
    "name" : "Mike0227",
    "difficulty" : "Medium",
    "genre": "Alt/Rock",
    "songNum" : 30,
    "score" : 72,
    "correct" : 23,
    "partiallyCorrect" : 6,
    "incorrect" : 1,
    "time" : "03:45",
    "avg" : "00:08"
  },
  {
    "name" : "Mike0227",
    "difficulty" : "Medium",
    "genre": "Pop",
    "songNum" : 30,
    "score" : 48,
    "correct" : 22,
    "partiallyCorrect" : 4,
    "incorrect" : 4,
    "time" : "02:55",
    "avg" : "00:06"
  },
  {
    "name" : "Chuckie",
    "difficulty" : "Medium",
    "genre": "Alt/Rock",
    "songNum" : 20,
    "score" : 33,
    "correct" : 14,
    "partiallyCorrect" : 5,
    "incorrect" : 1,
    "time" : "01:45",
    "avg" : "00:06"
  },
  {
    "name" : "Carson",
    "difficulty" : "Hard",
    "genre": "Pop",
    "songNum" : 22,
    "score" : 7,
    "correct" : 8,
    "partiallyCorrect" : 5,
    "incorrect" : 2,
    "time" : "01:47",
    "avg" : "00:06"
  },
  {
    "name" : "PoTheCat",
    "difficulty" : "Easy",
    "genre": "Pop",
    "songNum" : 10,
    "score" : 20,
    "correct" : 10,
    "partiallyCorrect" : 0,
    "incorrect" : 0,
    "time" : "00:45",
    "avg" : "00:05"
  },
  {
    "name" : "Mama Terry",
    "difficulty" : "Easy",
    "genre": "Pop",
    "songNum" : 20,
    "score" : 38,
    "correct" : 18,
    "partiallyCorrect" : 2,
    "incorrect" : 0,
    "time" : "01:42",
    "avg" : "00:06"
  },
  {
    "name" : "LeiaLove",
    "difficulty" : "Easy",
    "genre": "Pop",
    "songNum" : 30,
    "score" : 60,
    "correct" : 30,
    "partiallyCorrect" : 0,
    "incorrect" : 0,
    "time" : "04:10",
    "avg" : "00:09"
  },
  {
    "name" : "Larissa",
    "difficulty" : "Medium",
    "genre": "Random",
    "songNum" : 10,
    "score" : 20,
    "correct" : 10,
    "partiallyCorrect" : 0,
    "incorrect" : 0,
    "time" : "00:32",
    "avg" : "00:04"
  },
  {
    "name" : "xo_Marsha_ox",
    "difficulty" : "Medium",
    "genre": "Random",
    "songNum" : 10,
    "score" : 19,
    "correct" : 9,
    "partiallyCorrect" : 1,
    "incorrect" : 0,
    "time" : "00:36",
    "avg" : "00:04"
  },
  {
    "name" : "Larissa",
    "difficulty" : "Easy",
    "genre": "Random",
    "songNum" : 10,
    "score" : 16,
    "correct" : 6,
    "partiallyCorrect" : 4,
    "incorrect" : 0,
    "time" : "00:33",
    "avg" : "00:04"
  },
  {
    "name" : "SeanMDude",
    "difficulty" : "Hard",
    "genre": "Random",
    "songNum" : 30,
    "score" : 60,
    "correct" : 30,
    "partiallyCorrect" : 0,
    "incorrect" : 0,
    "time" : "03:50",
    "avg" : "00:08"
  },
  {
    "name" : "KarateKid01",
    "difficulty" : "Hard",
    "genre": "Random",
    "songNum" : 30,
    "score" : 25,
    "correct" : 10,
    "partiallyCorrect" : 5,
    "incorrect" : 15,
    "time" : "05:30",
    "avg" : "0:11"
  },
  {
    "name" : "Jane Doe",
    "difficulty" : "Hard",
    "genre": "Random",
    "songNum" : 30,
    "score" : 52,
    "correct" : 25,
    "partiallyCorrect" : 2,
    "incorrect" : 3,
    "time" : "03:57",
    "avg" : "00:08"
  },
  {
    "name" : "Jon-a-thon",
    "difficulty" : "Hard",
    "genre": "Random",
    "songNum" : 20,
    "score" : 40,
    "correct" : 20,
    "partiallyCorrect" : 0,
    "incorrect" : 0,
    "time" : "02:50",
    "avg" : "00:06"
  },
  {
    "name" : "SeanMDude",
    "difficulty" : "Easy",
    "genre": "Random",
    "songNum" : 10,
    "score" : 20,
    "correct" : 10,
    "partiallyCorrect" : 0,
    "incorrect" : 0,
    "time" : "01:10",
    "avg" : "00:03"
  },
  {
    "name" : "Wild1_83",
    "difficulty" : "Easy",
    "genre": "Random",
    "songNum" : 20,
    "score" : 36,
    "correct" : 16,
    "partiallyCorrect" : 4,
    "incorrect" : 0,
    "time" : "02:44",
    "avg" : "00:06"
  },
  {
    "name" : "Ryan Reynolds",
    "difficulty" : "Medium",
    "genre": "Random",
    "songNum" : 20,
    "score" : 29,
    "correct" : 13,
    "partiallyCorrect" : 3,
    "incorrect" : 4,
    "time" : "02:31",
    "avg" : "00:05"
  },
  {
    "name" : "Deadpool",
    "difficulty" : "Hard",
    "genre": "Pop",
    "songNum" : 30,
    "score" : 60,
    "correct" : 30,
    "partiallyCorrect" : 0,
    "incorrect" : 0,
    "time" : "04:05",
    "avg" : "00:09"
  },
  {
    "name" : "Carolina_ReaperXD",
    "difficulty" : "Medium",
    "genre": "Random",
    "songNum" : 30,
    "score" : 49,
    "correct" : 21,
    "partiallyCorrect" : 7,
    "incorrect" : 2,
    "time" : "03:26",
    "avg" : "00:07"
  },
  {
    "name" : "Carolina_ReaperXD",
    "difficulty" : "Hard",
    "genre": "Random",
    "songNum" : 20,
    "score" : 23,
    "correct" : 5,
    "partiallyCorrect" : 13,
    "incorrect" : 2,
    "time" : "02:34",
    "avg" : "00:06"
  },
  {
    "name" : "Mary_Has_A_Little_Lamb_Still",
    "difficulty" : "Hard",
    "genre": "Random",
    "songNum" : 20,
    "score" : 20,
    "correct" : 8,
    "partiallyCorrect" : 4,
    "incorrect" : 8,
    "time" : "02:42",
    "avg" : "00:06"
  },
  {
    "name" : "Margaret_Margarita",
    "difficulty" : "Hard",
    "genre": "Random",
    "songNum" : 10,
    "score" : 13,
    "correct" : 3,
    "partiallyCorrect" : 7,
    "incorrect" : 0,
    "time" : "01:04",
    "avg" : "00:03"
  },
  {
    "name" : "Wiley00Coyote",
    "difficulty" : "Hard",
    "genre": "Random",
    "songNum" : 10,
    "score" : 14,
    "correct" : 6,
    "partiallyCorrect" : 2,
    "incorrect" : 2,
    "time" : "01:03",
    "avg" : "00:03"
  },
  {
    "name" : "CallieGURL",
    "difficulty" : "Hard",
    "genre": "Random",
    "songNum" : 10,
    "score" : 13,
    "correct" : 5,
    "partiallyCorrect" : 3,
    "incorrect" : 2,
    "time" : "01:08",
    "avg" : "00:04"
  },
  {
    "name" : "CallieGURL",
    "difficulty" : "Easy",
    "genre": "Alt/Rock",
    "songNum" : 10,
    "score" : 10,
    "correct" : 2,
    "partiallyCorrect" : 6,
    "incorrect" : 2,
    "time" : "01:54",
    "avg" : "00:12"
  },
  {
    "name" : "KailynDatGirl28",
    "difficulty" : "Easy",
    "genre": "Alt/Rock",
    "songNum" : 10,
    "score" : 4,
    "correct" : 0,
    "partiallyCorrect" : 4,
    "incorrect" : 6,
    "time" : "01:34",
    "avg" : "00:10"
  },
  {
    "name" : "CallieGURL",
    "difficulty" : "Easy",
    "genre": "Alt/Rock",
    "songNum" : 10,
    "score" : 12,
    "correct" : 5,
    "partiallyCorrect" : 2,
    "incorrect" : 3,
    "time" : "01:27",
    "avg" : "00:09"
  },
]