DROP DATABASE IF EXISTS worddensity;

CREATE DATABASE worddensity;

USE worddensity;

CREATE TABLE webpages (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `webpage_url` VARCHAR(255) UNIQUE NOT NULL,
  `notes` VARCHAR(255) NULL,
  `date_added` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `date_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE tests (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `url_id` INT NOT NULL,
  `date_of_test` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `word_density_list` JSON,
  FOREIGN KEY (`url_id`) REFERENCES webpages(`id`)
);
